language: php

sudo: false

php:
  - 8.1
  - nightly

addons:
  postgresql: "15.4"

before_script:
  - make test/config/dbc.json test/db-scripts/create-database.sql
  - psql -U postgres <test/db-scripts/create-database.sql
  - touch .database-created

script: make run-unit-tests
