<?php

/**
 * Represents any information generated by invoking an action.
 * Can be passed to a ResultAssembler#assembleResult to be transformed into some other representation.
 */
interface EarthIT_CMIPREST_ActionResult { }
